name: cron

on:
  schedule:
  - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3"
      - run: mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins"
      - run: /usr/bin/defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES

      - run: yarn global add skpm
      - run: skpm create sketch-plugin-typescript --template=romansp/skpm-typescript
      - run: |
          cd sketch-plugin-typescript
          yarn install
          yarn lint
